modLoader="javafml"
loaderVersion="[39,)"
license="All rights reserved"
[[mods]]
modId="testmod" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Test Mod" #mandatory
logoFile="examplemod.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="BabaProg" #optional
description='''
'''
[[dependencies.testmod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[39,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.testmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
